server:
  port: 8892
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://MOVIE
          predicates:
            - Path=/movie/**
        - id: catalogRoute
          uri: lb://catalog
          predicates:
            - Path=/catalog/**
